/** @type {import('./excelParser').ParsedBomData} */
export const SAMPLE_BOM_DATA = {
  items: [
    { id: '1', componentName: 'Lidar Sensör Modülü', category: 'sensors', categoryLabel: 'Sensors', unitCost: 450, quantity: 4, totalCost: 1800, period: 'Q1', budget: null },
    { id: '2', componentName: 'Ultrasonik Mesafe Sensörü', category: 'sensors', categoryLabel: 'Sensors', unitCost: 25, quantity: 20, totalCost: 500, period: 'Q1', budget: null },
    { id: '3', componentName: 'Ana Kontrol İşlemcisi', category: 'processors', categoryLabel: 'Processors', unitCost: 120, quantity: 5, totalCost: 600, period: 'Q1', budget: null },
    { id: '4', componentName: 'Alüminyum Şasi', category: 'materials', categoryLabel: 'Materials', unitCost: 300, quantity: 2, totalCost: 600, period: 'Q1', budget: null },
    { id: '5', componentName: 'HMI Dokunmatik Ekran', category: 'interfaces', categoryLabel: 'Interfaces', unitCost: 150, quantity: 3, totalCost: 450, period: 'Q2', budget: null },
    { id: '6', componentName: 'SCADA Kontrol Yazılımı', category: 'interfaces', categoryLabel: 'Interfaces', unitCost: 500, quantity: 1, totalCost: 500, period: 'Q2', budget: null },
    { id: '7', componentName: 'Montaj İşçiliği', category: 'labor', categoryLabel: 'Labor', unitCost: 40, quantity: 100, totalCost: 4000, period: 'Q2', budget: null },
    { id: '8', componentName: 'Endüstriyel Görüş Kamerası', category: 'sensors', categoryLabel: 'Sensors', unitCost: 200, quantity: 6, totalCost: 1200, period: 'Q2', budget: null },
    { id: '9', componentName: 'Gömülü Mikrodenetleyici', category: 'processors', categoryLabel: 'Processors', unitCost: 15, quantity: 50, totalCost: 750, period: 'Q3', budget: null },
    { id: '10', componentName: 'Çelik Montaj Braketleri', category: 'materials', categoryLabel: 'Materials', unitCost: 5, quantity: 200, totalCost: 1000, period: 'Q3', budget: null },
    { id: '11', componentName: 'Kablo Gruplaması', category: 'electronics', categoryLabel: 'Electronics', unitCost: 80, quantity: 10, totalCost: 800, period: 'Q3', budget: null },
    { id: '12', componentName: 'Sistem Test İşçiliği', category: 'labor', categoryLabel: 'Labor', unitCost: 50, quantity: 80, totalCost: 4000, period: 'Q4', budget: null },
    { id: '13', componentName: 'Sıcaklık ve Nem Sensörü', category: 'sensors', categoryLabel: 'Sensors', unitCost: 30, quantity: 15, totalCost: 450, period: 'Q4', budget: null },
    { id: '14', componentName: 'Güç Kaynağı Ünitesi', category: 'electronics', categoryLabel: 'Electronics', unitCost: 90, quantity: 8, totalCost: 720, period: 'Q4', budget: null },
    { id: '15', componentName: 'Veri İletim Modülü', category: 'interfaces', categoryLabel: 'Interfaces', unitCost: 110, quantity: 5, totalCost: 550, period: 'Q4', budget: null },
  ],
  summary: {
    totalCost: 17920,
    itemCount: 15,
    avgUnitCost: 144.33,
    topCategory: {
      name: 'Labor',
      category: 'labor',
      cost: 8000,
      percentage: 44.64,
    },
    totalBudget: null,
    budgetVariance: null,
    budgetVariancePercent: null,
    hasTimeSeries: true,
  },
  aggregations: {
    byCategory: [
      { category: 'labor', label: 'Labor', cost: 8000, percentage: 44.64, count: 2 },
      { category: 'sensors', label: 'Sensors', cost: 3950, percentage: 22.04, count: 4 },
      { category: 'electronics', label: 'Electronics', cost: 1520, percentage: 8.48, count: 2 },
      { category: 'materials', label: 'Materials', cost: 1600, percentage: 8.93, count: 2 },
      { category: 'interfaces', label: 'Interfaces', cost: 1500, percentage: 8.37, count: 3 },
      { category: 'processors', label: 'Processors', cost: 1350, percentage: 7.53, count: 2 },
    ],
    topCostDrivers: [
      { componentName: 'Montaj İşçiliği', category: 'labor', categoryLabel: 'Labor', totalCost: 4000, quantity: 100, unitCost: 40 },
      { componentName: 'Sistem Test İşçiliği', category: 'labor', categoryLabel: 'Labor', totalCost: 4000, quantity: 80, unitCost: 50 },
      { componentName: 'Lidar Sensör Modülü', category: 'sensors', categoryLabel: 'Sensors', totalCost: 1800, quantity: 4, unitCost: 450 },
      { componentName: 'Endüstriyel Görüş Kamerası', category: 'sensors', categoryLabel: 'Sensors', totalCost: 1200, quantity: 6, unitCost: 200 },
      { componentName: 'Çelik Montaj Braketleri', category: 'materials', categoryLabel: 'Materials', totalCost: 1000, quantity: 200, unitCost: 5 },
      { componentName: 'Kablo Gruplaması', category: 'electronics', categoryLabel: 'Electronics', totalCost: 800, quantity: 10, unitCost: 80 },
      { componentName: 'Gömülü Mikrodenetleyici', category: 'processors', categoryLabel: 'Processors', totalCost: 750, quantity: 50, unitCost: 15 },
      { componentName: 'Güç Kaynağı Ünitesi', category: 'electronics', categoryLabel: 'Electronics', totalCost: 720, quantity: 8, unitCost: 90 },
      { componentName: 'Ana Kontrol İşlemcisi', category: 'processors', categoryLabel: 'Processors', totalCost: 600, quantity: 5, unitCost: 120 },
      { componentName: 'Veri İletim Modülü', category: 'interfaces', categoryLabel: 'Interfaces', totalCost: 550, quantity: 5, unitCost: 110 },
    ],
    costTrend: [
      { period: 'Q1', cost: 3500, itemCount: 4 },
      { period: 'Q2', cost: 6150, itemCount: 4 },
      { period: 'Q3', cost: 2550, itemCount: 3 },
      { period: 'Q4', cost: 5720, itemCount: 4 },
    ],
  },
  meta: {
    fileName: 'ornek-bom-verisi.xlsx',
    sheetName: 'Sheet1',
    rowCount: 15,
    parsedAt: new Date().toISOString(),
  },
};

export const SAMPLE_FILE_PATH = '/samples/ornek-bom-verisi.xlsx';
